<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Biswajit-PC" name="Default test" tests="7" failures="1" timestamp="21 May 2015 13:15:45 GMT" time="32.837" errors="0">
  <testcase name="contactUs" time="6.447" classname="com.webtek.test.SanityTest2"/>
  <testcase name="contactUs" time="4.631" classname="com.webtek.test.SanityTest2"/>
  <testcase name="contactUs" time="4.984" classname="com.webtek.test.SanityTest2"/>
  <testcase name="contactUs" time="5.303" classname="com.webtek.test.SanityTest2"/>
  <testcase name="contactUs" time="4.743" classname="com.webtek.test.SanityTest2"/>
  <testcase name="contactUs" time="4.495" classname="com.webtek.test.SanityTest2"/>
  <testcase name="contactUs" time="2.021" classname="com.webtek.test.SanityTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.ui.Select.escapeQuotes(Select.java:298)
	at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:113)
	at com.webtek.action.ContactUsAction.execute(ContactUsAction.java:55)
	at com.webtek.test.SanityTest2.contactUs(SanityTest2.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- contactUs -->
</testsuite> <!-- Default test -->
